variables:
  GCP_PROJECT_ID: "or-tfconfig-dec-exp-prod"
  REGION: "europe-west2"
  REPO_NAME: "rca-task-info"
  REGISTRY: "${REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${REPO_NAME}"

stages:
  - build
  - deploy

.gcp-auth:
  before_script:
    - echo "$GCP_SA_KEY" > /tmp/key.json
    - gcloud auth activate-service-account --key-file=/tmp/key.json
    - gcloud config set project ${GCP_PROJECT_ID}
    - gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet
  after_script:
    - rm -f /tmp/key.json
  only:
    - main

build-frontend:
  extends: .gcp-auth
  stage: build
  image: google/cloud-sdk:slim
  script:
    - gcloud builds submit --tag ${REGISTRY}/frontend:${CI_COMMIT_SHORT_SHA} .
    - gcloud artifacts docker tags add ${REGISTRY}/frontend:${CI_COMMIT_SHORT_SHA} ${REGISTRY}/frontend:latest

build-api:
  extends: .gcp-auth
  stage: build
  image: google/cloud-sdk:slim
  script:
    - gcloud builds submit --tag ${REGISTRY}/api:${CI_COMMIT_SHORT_SHA} ./api
    - gcloud artifacts docker tags add ${REGISTRY}/api:${CI_COMMIT_SHORT_SHA} ${REGISTRY}/api:latest

terraform-deploy:
  stage: deploy
  image: hashicorp/terraform:latest
  before_script:
    - echo "$GCP_SA_KEY" > key.json
    - export GOOGLE_APPLICATION_CREDENTIALS=key.json
  script:
    - cd terraform
    - terraform init
    - terraform apply -auto-approve -var="project_id=${GCP_PROJECT_ID}" -var="api_service_account=scheduler-sa@or-tfconfig-dec-exp-prod.iam.gserviceaccount.com" -var="deployer_sa_email=${DEPLOYER_SA_EMAIL}"
  after_script:
    - rm -f key.json
  only:
    - main
